spring:
  application:
    name: planet-service
  data:
    mongodb:
      database: planet
      uri: mongodb://localhost:27017
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

crew-service:
  crewsUrl: http://crew-service/v1/crews
  crewByIdUrl: http://crew-service/v1/crews/{crewId}
  ribbon:
    listOfServers: localhost:8092